version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: ZPMS
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ZPMS
      DB_USER: root
      DB_PASS: root@123
